LibrarieDemo/Controllers/CategorieController.cs
using LibrarieDemo.Data;
using LibrarieDemo.Models;
using Microsoft.AspNetCore.Mvc;

namespace LibrarieDemo.Controllers
{
    public class CategorieController : Controller
    {
        private readonly DbContextObiectConex _db;
        public CategorieController(DbContextObiectConex db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<Categorie> CategorieLista=_db.Categoriile;
            return View(CategorieLista);
        }
        //Get
        public IActionResult Creare()
        {
            return View();
        }
        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Creare(Categorie obiect)
        {
            _db.Categoriile.Add(obiect);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }


    }
}

LibrarieDemo/Controllers/ProdusController.cs
using LibrarieDemo.Data;
using LibrarieDemo.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace LibrarieDemo.Controllers
{
    public class ProdusController : Controller
    {

        private readonly DbContextObiectConex _db;
        private readonly IWebHostEnvironment _hostEnvironment;//e deja adaugat ca dependency injection in asp.net trebuie doar sa il extrag
        public ProdusController(DbContextObiectConex db, IWebHostEnvironment hostEnvironment)
        {
            _db = db;
            _hostEnvironment = hostEnvironment;
        }

        public IActionResult Index()
        {
            IEnumerable<Produs> ProduseLista = _db.Produsele;
            return View(ProduseLista);
        }
        //Get Creare
        public IActionResult Creare()
        {
            IEnumerable<SelectListItem> CategorieLista = _db.Categoriile.Select(
                u=>new SelectListItem
                {
                    Text= u.Nume,
                    Value=u.Id.ToString()
                });
            ViewData["CategorieLista"] = CategorieLista;
            return View();
        }
        //Post Creare
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Creare(Produs obiect,IFormFile? fisier)
        {
            if (ModelState.IsValid)
            {
                string wwwRootPath = _hostEnvironment.WebRootPath;
                if(fisier!=null)
                {
                    //upload
                    string fisierNume=Guid.NewGuid().ToString();//dam rename la fiecare fisier uploadat sa nu se incurce 2 fisiere similare
                    var uploadat=Path.Combine(wwwRootPath,@"imagini\produse");
                    var extensie = Path.GetExtension(fisier.FileName);
                    //copiem fisierul uploadat in folder
                    using(var fisierStreams = new FileStream(Path.Combine(uploadat, fisierNume + extensie),FileMode.Create))
                    {
                        fisier.CopyTo(fisierStreams);
                    }
                    obiect.ImagineUrl = @"\imagini\produse\" + fisierNume + extensie;

                }



                _db.Produsele.Add(obiect);
                _db.SaveChanges();
                return RedirectToAction("Index");

            }
            return View();

        }
        //Get Editare
        public IActionResult Editare(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            else
            {
                IEnumerable<SelectListItem> CategorieLista = _db.Categoriile.Select(
                u => new SelectListItem
                {
                    Text = u.Nume,
                    Value = u.Id.ToString()
                });
                ViewData["CategorieLista"] = CategorieLista;
               
                var produsDinDB = _db.Produsele.FirstOrDefault(u => u.Id == id);
                return View(produsDinDB);
            }

        }
        //Post Editare
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Editare(Produs obiect,IFormFile? fisier)
        {
            if (ModelState.IsValid)
            {
                string wwwRootPath = _hostEnvironment.WebRootPath;
                if (fisier != null)
                {
                    //upload
                    string fisierNume = Guid.NewGuid().ToString();//dam rename la fiecare fisier uploadat sa nu se incurce 2 fisiere similare
                    var uploadat = Path.Combine(wwwRootPath, @"imagini\produse");
                    var extensie = Path.GetExtension(fisier.FileName);
                    //stergem fisierul in caz de update
                    if(obiect.ImagineUrl!=null)
                    {
                        var vecheaPozaPath = Path.Combine(wwwRootPath, obiect.ImagineUrl.TrimStart('\\'));//caracterul "\" este un escape caracter si trebuie sa scriem de 2 ori
                        if(System.IO.File.Exists(vecheaPozaPath))
                        {
                            System.IO.File.Delete(vecheaPozaPath);
                        }

                    }
                    //copiem fisierul uploadat in folder
                    using (var fisierStreams = new FileStream(Path.Combine(uploadat, fisierNume + extensie), FileMode.Create))
                    {
                        fisier.CopyTo(fisierStreams);
                    }
                    obiect.ImagineUrl = @"\imagini\produse\" + fisierNume + extensie;

                }





                _db.Produsele.Update(obiect);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            
            return View();
        }




        //Get Stergere
        public IActionResult Stergere(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            else
            {
                var produsDinDB = _db.Produsele.FirstOrDefault(u => u.Id == id);
                return View(produsDinDB);
            }
        }
        //Post Stergere
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Stergere(Produs obiect)
        {
            if (ModelState.IsValid)
            {
                _db.Produsele.Remove(obiect);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

LibrarieDemo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LibrarieDemo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LibrarieDemo.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css"> @*boostrap icons*@
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LibrarieDemo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categorie" asp-action="Index">Categorie Lista</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produs" asp-action="Index">Produs Lista</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - LibrarieDemo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>